### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by eileenfan** [alt236/USB-Device-Info---Android#23]
//package name: aws.apps.usbDeviceEnumerator
//version: 1.0.0
 java.lang.NullPointerException
 	at aws.apps.usbDeviceEnumerator.ui.progress.ProgressDialogFragment.setTitle(ProgressDialogFragment.java:48)
 	at aws.apps.usbDeviceEnumerator.ui.progress.ProgressDialogControl.updateProgress(ProgressDialogControl.java:37)
 	at aws.apps.usbDeviceEnumerator.ui.dbupdate.FileDownloadTask.onProgressUpdate(FileDownloadTask.java:137)
 	at aws.apps.usbDeviceEnumerator.ui.dbupdate.FileDownloadTask.onProgressUpdate(FileDownloadTask.java:21)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:647)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by nanderer** [comment]
I guess if I would be an developer I would ask: What Android version, how to reproduce?
