### ISSUE TITLE
App crash if dir.getFiles returns null - Nougat

### ISSUE THREAD

**Issue by alt236** [alt236/USB-Device-Info---Android#8]
ava.lang.RuntimeException: Unable to start activity ComponentInfo{aws.apps.usbDeviceEnumerator/aws.apps.usbDeviceEnumerator.ui.main.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
    at uk.co.alt236.usbdeviceenumerator.sysbususb.SysBusUsbManager.populateList(SysBusUsbManager.java:77)
    at uk.co.alt236.usbdeviceenumerator.sysbususb.SysBusUsbManager.getUsbDevices(SysBusUsbManager.java:61)
    at aws.apps.usbDeviceEnumerator.ui.main.MainActivity.refreshUsbDevices(MainActivity.java:203)
    at aws.apps.usbDeviceEnumerator.ui.main.MainActivity.onCreate(MainActivity.java:132)
    at android.app.Activity.performCreate(Activity.java:6664)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
    ... 9 more

**Comment by alt236** [comment]
Fixed by #13
